# Generated by Django 4.2.7 on 2023-11-27 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='target',
            fields=[
                ('id_email_hashed', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('has_read', models.BooleanField(default=False)),
                ('has_open', models.BooleanField(default=False)),
                ('has_logged', models.BooleanField(default=False)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.campagne_fish')),
            ],
        ),
    ]
