# Generated by Django 4.2.7 on 2023-11-28 18:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_target_id_email_hashed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='id_email_hashed',
        ),
        migrations.AddField(
            model_name='target',
            name='id_email_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
